[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hcv-gaps"
version = "0.1.0"
description = "Code to measure Housing Choice Voucher gaps"
authors = [{ name = "Shane Dabney", email = "sdabney@fsu.edu" }]
readme = "README.md"
requires-python = ">=3.9"

# Setuptools looks inside the /src layout
[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
